name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create env file
        run: |
          echo "GEMINI_API_KEY=dummy" > .env
          echo "GEMINI_API_KEY=dummy" > .env.example

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.jks

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          $ANDROID_HOME/build-tools/36.0.0/apksigner sign \
          --ks release.jks \
          --ks-pass pass:${{ secrets.STORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --ks-key-alias ${{ secrets.KEY_ALIAS }} \
          app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IronMass-APK
          path: app/build/outputs/apk/release/*.apk
